### ISSUE TITLE
NUI backend breaks with winbar

### ISSUE THREAD

**Issue by ecosse3** [stevearc/dressing.nvim#45]
**Describe the bug**

**System information**

- OS: **MacOS**
- Neovim version: **NVIM v0.8.0-dev+1816-g9745941ef**
- Is this related to a specific `vim.ui.select` backend? If so, which one? **nui**
- Dressing config:

```lua
require('dressing').setup({
  input = {
    -- Set to false to disable the vim.ui.input implementation
    enabled = true,

    -- Default prompt string
    default_prompt = "Input:",

    -- Can be 'left', 'right', or 'center'
    prompt_align = "left",

    -- When true, <Esc> will close the modal
    insert_only = true,

    -- These are passed to nvim_open_win
    anchor = "SW",
    border = EcoVim.ui.float.border or "rounded",
    -- 'editor' and 'win' will default to being centered
    relative = "cursor",

    -- These can be integers or a float between 0 and 1 (e.g. 0.4 for 40%)
    prefer_width = 40,
    width = nil,
    -- min_width and max_width can be a list of mixed types.
    -- min_width = {20, 0.2} means "the greater of 20 columns or 20% of total"
    max_width = { 140, 0.9 },
    min_width = { 20, 0.2 },

    -- Window transparency (0-100)
    winblend = 0,
    -- Change default highlight groups (see :help winhl)
    winhighlight = "",

    override = function(conf)
      -- This is the config that will be passed to nvim_open_win.
      -- Change values here to customize the layout
      return conf
    end,

    -- see :help dressing_get_config
    get_config = nil,
  },

  select = {
    -- Set to false to disable the vim.ui.select implementation
    enabled = true,

    -- Priority list of preferred vim.select implementations
    backend = { "telescope", "nui", "fzf", "builtin" },

    -- Options for nui Menu
    nui = {
      position = {
        row = 1,
        col = 0,
      },
      size = nil,
      relative = "cursor",
      border = {
        style = EcoVim.ui.float.border or "rounded",
        text = {
          top_align = "right",
        },
      },
      max_width = 80,
      max_height = 40,
    },


    -- see :help dressing_get_config
    get_config = function(opts)
      if opts.kind == 'codeaction' then
        return {
          backend = 'nui',
          nui = {
            relative = 'cursor',
            max_width = 80,
          }
        }
      end
    end
  },
})
```

**To Reproduce**

1. Use winbar of nvim 0.8

If possible, provide a minimal file that will trigger the issue (see
[tests/manual](https://github.com/stevearc/dressing.nvim/tree/master/tests/manual)
for examples of short ways to call `vim.ui.*`):

Somehow it works good with test. Just breaks when using my config and code actions/rename.
![image](https://user-images.githubusercontent.com/17691791/171917113-658aa83a-fe9b-4cb4-8e55-586d518d704e.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/17691791/171916989-3f9a99fd-c443-4655-8aae-de7bc3f00b5f.png)

**Additional context**
I have winbar configured with nvim 0.8 and then `nui` backed stops working and each time I try to use code action with vim.ui.select or rename with vim.ui.input it throws error.

Looks like winbar is trying to be attached to nui window and it doesn't have enough space or sth like that.
I've added "DressingInput" filetype and "DressingSelect" filetype to excluded of winbar but it still doesn't work. I can tell that it works great with Telescope (which has filetype of TelescopePrompt) added to excluded filetypes.

My autocmd for winbar:
```lua
vim.api.nvim_create_autocmd({ "CursorMoved", "BufWinEnter", "BufFilePost" }, {
  callback = function()
    local winbar_filetype_exclude = {
      "help",
      "startify",
      "dashboard",
      "packer",
      "neogitstatus",
      "NvimTree",
      "Trouble",
      "alpha",
      "lir",
      "Outline",
      "spectre_panel",
      "toggleterm",
      "TelescopePrompt",
      "DressingInput",
      "DressingSelect",
    }

    if vim.tbl_contains(winbar_filetype_exclude, vim.bo.filetype) then
      vim.opt_local.winbar = nil
      return
    end

    local value = require("winbar").gps()

    if value == nil then
      value = require("winbar").filename()
    end

    vim.opt_local.winbar = value
  end,
})
```

I also realized that if the error shows, sometimes "Code actions" are showing and when I click enter everything seems to work fine. Just error is showing each time:

![image](https://user-images.githubusercontent.com/17691791/171918646-a889f7de-7661-45fc-800c-6a74a08cc70f.png)

Then press enter and it shows correctly:
![image](https://user-images.githubusercontent.com/17691791/171918699-7cb31138-a661-4a59-b248-8bcfe93ff704.png)

Same with vim.ui.input.

Does anyone else have this issue when using winbar with nui prompt?

**Comment by stevearc** [comment]
Without a repro this will be difficult to address. I just pushed up a commit that exposes more of the underlying config options for nui, and additionally sets the filetype by default to be `DressingSelect` (previously it was empty, which you can verify with `:set filetype?`). Hopefully that should be enough to get your filetype exclusion working.

Some other exclusions you may want to use are
```lua
-- Inside a floating window
vim.api.nvim_win_get_config(0).relative ~= ""
-- Inside an unnamed buffer
vim.api.nvim_buf_get_name(0) == ""
-- Inside a non-normal buffer (e.g. quickfix, terminal, etc)
vim.api.nvim_buf_get_option(0, 'buftype') ~= ""
```

**Comment by ecosse3** [comment]
Unfortunately now I have different issue with Select (code actions) and it breaks even without `winbar` implementation.

![image](https://user-images.githubusercontent.com/17691791/172052322-9ab8a274-afd7-4f19-9cb4-038f04161db2.png)

`vim.ui.input` with nui works fine without winbar. Still same issue when using winbar.
I've checked and `vim.bo.filetype` is "DressingSelect" as expected now, but still breaks.

My config can be installed via https://github.com/ecosse3/nvim but unfortunately I'm not able to setup Docker (Alpine Linux) with Neovim Nightly for testing (just 0.7 is available).

**Comment by ecosse3** [comment]
@stevearc Thanks. Now NUI select works with code actions. Unfortunately, it has more height than expected:

![image](https://user-images.githubusercontent.com/17691791/172481655-bf0c190e-0c07-4fc2-97aa-a70cd4b35b9b.png)

With `vim.ui.input` I'm still experiencing the same issue. Error, and then after <Enter> it works fine:

![image](https://user-images.githubusercontent.com/17691791/172481788-d69ff07f-58be-4547-b685-011e9936e355.png)

**Comment by stevearc** [comment]
You can adjust the height by changing the `min_height` value in the nui config area.

For the vim.ui.input error, you're just going to have to change how you set the winbar. Right now you're doing it on CursorMoved, so it runs as soon as the input float window is opened, and critically, *before* the filetype is set. This is why I recommended using some of those other exclusion rules, like unnamed buffers or floating windows. Probably the safest thing would be to check the height of the window before setting it. Or you could wrap the call to nvim_buf_set_option with pcall to silence the error.

**Comment by ecosse3** [comment]
@stevearc Thanks, everything works as expected now. Checking if window is floating helped fixing this error.
